#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math, re


class Receiver:
    def __init__(self):
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))
        self.port = self.socket.getsockname()[1]
        self.log("Bound to port %d" % self.port)
        self.LoM = []
        self.count = 0

        self.remote_host = None
        self.remote_port = None

    def send(self, message):
        self.socket.sendto(json.dumps(message).encode('utf-8'), (self.remote_host, self.remote_port))

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def run(self):
        while True:
            socks = select.select([self.socket], [], [])[0]
            for conn in socks:
                data, addr = conn.recvfrom(65535)

                # Grab the remote host/port if we don't already have it
                if self.remote_host is None:
                    self.remote_host = addr[0]
                    self.remote_port = addr[1]

                msg = json.loads(data.decode('utf-8'))

                #print("hopefully this works:" + str(msg["sequence"]))

                substring = msg["data"][13:19]
                #print("this is msg data recieved:" + str(msg))
                self.count += 1

                #print(str(self.LoM))
                #how can all the data be transmitted to the point where theres an error, yet it still not work properly

                #new ack

                if(substring not in self.LoM):
                    #self.count += 1
                    self.LoM.append(substring)

                    self.log("Received data message %s" % msg)
                    # Print out the data to stdout
                    print(msg["data"], end='', flush=True)

                    # Always send back an ack
                    self.send({ "type": "ack", "sequence": msg["sequence"] })

        return


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='receive data')
    args = parser.parse_args()
    sender = Receiver()
    sender.run()
